apiVersion: v1
kind: Service
metadata:
  name: { { include "cert-manager-webhook-vercel.fullname" . } }
  namespace: { { .Release.Namespace | quote } }
  labels:
    app: { { include "cert-manager-webhook-vercel.name" . } }
    chart: { { include "cert-manager-webhook-vercel.chart" . } }
    release: { { .Release.Name } }
    heritage: { { .Release.Service } }
spec:
  type: { { .Values.service.type } }
  ports:
    - port: { { .Values.service.port } }
      targetPort: https
      protocol: TCP
      name: https
  selector:
    app: { { include "cert-manager-webhook-vercel.name" . } }
    release: { { .Release.Name } }
