---
affinity: {}
certManager:
  namespace: cert-manager
  serviceAccountName: cert-manager
deployment:
  logLevel: 6
  secretKey: token
  secretName: vercel-credentials
  teamId: ''
  teamSlug: ''
fullnameOverride: ''
# The GroupName here is used to identify your company or business unit that
# created this webhook.
# For example, this may be "acme.mycompany.com".
# This name will need to be referenced in each Issuer's `webhook` stanza to
# inform cert-manager of where to send ChallengePayload resources in order to
# solve the DNS01 challenge.
# This group name should be **unique**, hence using your own company's domain
# here is recommended.
groupName: acme.rhythmbhiwani.com
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/rhythmbhiwani/cert-manager-webhook-vercel
  tag: latest
nameOverride: ''
nodeSelector: {}
resources: {}
service:
  port: 443
  type: ClusterIP
tolerations: []
#  memory: 128Mi
  # requests:
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi